# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="/anaconda3/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH=/Users/tandav/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

#ZSH_THEME=robbyrussell
ZSH_THEME=tandav
#ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status virtualenv)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
DEFAULT_USER='tandav'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=""
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(icons_test)

# Add this separator after each output:
function echo_blank() {
  #echo "------------------------------------------------------------"
  # echo
}
precmd_functions+=echo_blank

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# cd to folder
alias doc="cd ~/Documents/"
alias u="cd ~/Documents/Ultrasonic-Stethoscope"
alias nt="cd ~/Documents/Notes"
alias parsers="cd ~/Documents/parsers && source .venv/bin/activate"
# alias uv="cd ~/Documents/Ultrasonic-Stethoscope/arduino && source ./env/bin/activate"
alias uv="cd ~/Documents/Ultrasonic-Stethoscope && source activate uv"
# alias uv="cd ~/Documents/Ultrasonic-Stethoscope && source activate uv-intel"
alias dt="cd ~/Desktop"
alias dw="cd ~/Downloads"

# apps & tools
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias emacs="emacs -nw"
alias net="sudo tshark -i en0 -T fields -e frame.time -e ip.src -e dns.qry.name -Y "dns.flags.response eq 0""
# alias net="sudo tshark -i en0 -T fields -e frame.number -e frame.time -e ip.src -e dns.qry.name -Y "dns.flags.response eq 0""
# alias net="sudo tshark -i en0 -T fields -e frame.number -e ip.src -e dns.qry.name -Y "dns.flags.response eq 0""
alias termdown="termdown -b"
alias weather="finger voronezh@graph.no"
alias wttr="curl wttr.in/voronezh"
alias speedtest="curl -s  https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python"
alias mtop="open /Applications/Utilities/Activity\ Monitor.app"
alias docker_size="du -h /Users/tandav/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2"

# netcracker/oracle
alias sqlcl="/Applications/SQLDeveloper.app/Contents/Resources/sqldeveloper/sqldeveloper/bin/sql"
alias nk_cli="sqlcl system/oracle@localhost:1521:xe"
alias nk="open -a DataGrip & docker start -a netcracker_db"
alias nks="docker stop netcracker_db"

# shortcuts
alias n="subl ~/Documents/Notes"
alias ns="subl ~/Documents/Notes"
alias kn="subl ~/Documents/knowledge-map"
alias o="open"
alias python="python3.6"
alias p3="python3.6"
alias p3a="/anaconda3/bin/python3"
alias p3_old="/usr/local/Cellar/python3/3.6.3/bin/python3"
alias s="subl"
alias rc="subl ~/.zshrc"
# activate env/ virtualenv
alias ve="source env/bin/activate"
alias jn="jupyter notebook"

# websites
alias wm="open https://www.youtube.com/playlist\?list\=PL4qBE1-4ZNC0Wam6r8MaZoUfZ8ektEVYe"
alias gist="open https://gist.github.com/tandav"
alias wf="open https://workflowy.com"
alias yt="open https://www.youtube.com"
alias gh="open https://github.com"
alias map="open https://github.com/tandav/life#my-life"
